"""
Professional DOCX report generator with HackerOne/Bugcrowd style formatting.
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
import logging

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml.shared import OxmlElement, qn
    from docx.oxml.ns import nsdecls
    from docx.oxml import parse_xml
except ImportError:
    Document = None
    print("Warning: python-docx not installed. DOCX reports will not be available.")

@dataclass
class VulnerabilityDetails:
    """Detailed vulnerability information for professional reporting."""
    title: str
    severity: str
    cvss_score: float
    description: str
    impact: str
    reproduction_steps: List[str]
    proof_of_concept: str
    affected_endpoints: List[str]
    request_response: Dict[str, str]
    remediation: str
    references: List[str]
    discovery_method: str

class ProfessionalDocxReportGenerator:
    """Generate professional vulnerability reports in DOCX format."""
    
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        self.logger = logging.getLogger(__name__)
        
        if Document is None:
            raise ImportError("python-docx is required for DOCX report generation. Install with: pip install python-docx")
    
    def generate_report(self, scan_results: Dict[str, Any], target: str) -> str:
        """Generate a comprehensive DOCX vulnerability report."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"bughunter_professional_report_{timestamp}.docx"
        filepath = os.path.join(self.output_dir, filename)
        
        # Ensure output directory exists
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Create document
        doc = Document()
        
        # Set up document styles
        self._setup_document_styles(doc)
        
        # Generate report content
        self._add_title_page(doc, target, timestamp)
        self._add_executive_summary(doc, scan_results)
        self._add_methodology(doc)
        self._add_vulnerability_details(doc, scan_results)
        self._add_recommendations(doc)
        self._add_appendix(doc, scan_results)
        
        # Save document
        doc.save(filepath)
        self.logger.info(f"Professional DOCX report saved: {filepath}")
        
        return filepath
    
    def _setup_document_styles(self, doc: Document):
        """Set up document styles and formatting."""
        # Define custom styles
        styles = doc.styles
        
        # Title style
        if 'Custom Title' not in [s.name for s in styles]:
            title_style = styles.add_style('Custom Title', 1)  # 1 = paragraph style
            title_style.font.name = 'Arial'
            title_style.font.size = Pt(24)
            title_style.font.bold = True
            title_style.font.color.rgb = RGBColor(0, 51, 102)  # Dark blue
            title_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
            title_style.paragraph_format.space_after = Pt(12)
        
        # Heading style
        if 'Custom Heading' not in [s.name for s in styles]:
            heading_style = styles.add_style('Custom Heading', 1)
            heading_style.font.name = 'Arial'
            heading_style.font.size = Pt(16)
            heading_style.font.bold = True
            heading_style.font.color.rgb = RGBColor(0, 51, 102)
            heading_style.paragraph_format.space_before = Pt(12)
            heading_style.paragraph_format.space_after = Pt(6)
    
    def _add_title_page(self, doc: Document, target: str, timestamp: str):
        """Add professional title page."""
        # Title
        title = doc.add_paragraph()
        title.style = 'Custom Title'
        title.add_run("Security Assessment Report").font.size = Pt(28)
        
        # Subtitle
        subtitle = doc.add_paragraph()
        subtitle.style = 'Custom Title'
        subtitle.add_run("Comprehensive Web Application Vulnerability Scan").font.size = Pt(18)
        subtitle.add_run("\n").font.size = Pt(18)
        subtitle.add_run("Generated by BugHunter Professional Scanner").font.size = Pt(14)
        subtitle.add_run("\n").font.size = Pt(14)
        subtitle.add_run(f"Target: {target}").font.size = Pt(14)
        subtitle.add_run("\n").font.size = Pt(14)
        subtitle.add_run(f"Date: {datetime.now().strftime('%B %d, %Y')}").font.size = Pt(14)
        
        # Add some spacing
        doc.add_paragraph("\n" * 10)
        
        # Confidentiality notice
        notice = doc.add_paragraph()
        notice.alignment = WD_ALIGN_PARAGRAPH.CENTER
        notice_run = notice.add_run("CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY")
        notice_run.font.bold = True
        notice_run.font.color.rgb = RGBColor(204, 0, 0)  # Red
        notice_run.font.size = Pt(12)
    
    def _add_executive_summary(self, doc: Document, scan_results: Dict[str, Any]):
        """Add executive summary section."""
        doc.add_page_break()
        
        # Section heading
        heading = doc.add_heading("Executive Summary", level=1)
        heading.style = 'Custom Heading'
        
        # Summary content
        vulnerabilities = scan_results.get('vulnerabilities', [])
        vuln_count = len(vulnerabilities)
        
        # Severity breakdown
        severity_counts = {'Critical': 0, 'High': 0, 'Medium': 0, 'Low': 0}
        for vuln in vulnerabilities:
            severity = vuln.get('severity', 'Low')
            if severity in severity_counts:
                severity_counts[severity] += 1
        
        # Executive summary paragraph
        summary_text = f"""
This security assessment was conducted on {scan_results.get('target', 'the target application')} 
using BugHunter Professional Scanner, a comprehensive vulnerability testing framework. 
The assessment identified {vuln_count} security vulnerabilities across various categories.

The vulnerability distribution is as follows:
• Critical: {severity_counts['Critical']} vulnerabilities
• High: {severity_counts['High']} vulnerabilities  
• Medium: {severity_counts['Medium']} vulnerabilities
• Low: {severity_counts['Low']} vulnerabilities

This assessment utilized automated scanning techniques combined with manual verification 
to ensure accuracy and reduce false positives. Each identified vulnerability has been 
thoroughly analyzed and includes detailed reproduction steps, impact assessment, and 
remediation recommendations.
"""
        
        doc.add_paragraph(summary_text)
        
        # Risk assessment table
        self._add_risk_assessment_table(doc, severity_counts)
    
    def _add_risk_assessment_table(self, doc: Document, severity_counts: Dict[str, int]):
        """Add risk assessment table."""
        doc.add_paragraph("\nRisk Assessment Summary:")
        
        table = doc.add_table(rows=1, cols=4)
        table.style = 'Table Grid'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        
        # Header row
        header_cells = table.rows[0].cells
        headers = ['Severity', 'Count', 'Risk Level', 'Business Impact']
        for i, header in enumerate(headers):
            header_cells[i].text = header
            header_cells[i].paragraphs[0].runs[0].font.bold = True
        
        # Data rows
        risk_data = [
            ('Critical', severity_counts['Critical'], 'Very High', 'Immediate action required'),
            ('High', severity_counts['High'], 'High', 'Priority remediation needed'),
            ('Medium', severity_counts['Medium'], 'Medium', 'Plan for next release cycle'),
            ('Low', severity_counts['Low'], 'Low', 'Monitor and address during maintenance')
        ]
        
        for severity, count, risk, impact in risk_data:
            row_cells = table.add_row().cells
            row_cells[0].text = severity
            row_cells[1].text = str(count)
            row_cells[2].text = risk
            row_cells[3].text = impact
            
            # Color code severity
            if severity == 'Critical':
                row_cells[0].paragraphs[0].runs[0].font.color.rgb = RGBColor(204, 0, 0)
            elif severity == 'High':
                row_cells[0].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 102, 0)
            elif severity == 'Medium':
                row_cells[0].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 204, 0)
            else:
                row_cells[0].paragraphs[0].runs[0].font.color.rgb = RGBColor(0, 153, 0)
    
    def _add_methodology(self, doc: Document):
        """Add testing methodology section."""
        doc.add_heading("Testing Methodology", level=1)
        
        methodology_text = """
This security assessment was conducted using a comprehensive methodology that combines 
automated vulnerability scanning with manual verification techniques. The assessment 
covered the following areas:

1. **OWASP Top 10 Testing**
   • Injection flaws (SQL, NoSQL, LDAP, XPath, etc.)
   • Broken authentication and session management
   • Sensitive data exposure
   • XML external entities (XXE)
   • Broken access control
   • Security misconfigurations
   • Cross-site scripting (XSS)
   • Insecure deserialization
   • Components with known vulnerabilities
   • Insufficient logging and monitoring

2. **Advanced Security Testing**
   • Server-side request forgery (SSRF)
   • Business logic vulnerabilities
   • Race conditions
   • Cryptographic weaknesses
   • File upload vulnerabilities
   • API security issues
   • WebSocket security
   • Authentication bypass techniques

3. **Infrastructure Assessment**
   • SSL/TLS configuration analysis
   • Security headers evaluation
   • Network reconnaissance
   • Subdomain enumeration
   • Directory and file discovery

4. **Testing Approach**
   • Automated scanning with BugHunt Professional Scanner
   • Manual verification of automated findings
   • Proof-of-concept development for critical issues
   • False positive reduction through manual analysis
   • Rate limiting and stealth techniques to avoid detection

All testing was conducted in a responsible manner with appropriate rate limiting 
to minimize impact on the target application and infrastructure.
"""
        
        doc.add_paragraph(methodology_text)
    
    def _add_vulnerability_details(self, doc: Document, scan_results: Dict[str, Any]):
        """Add detailed vulnerability information."""
        vulnerabilities = scan_results.get('vulnerabilities', [])
        
        if not vulnerabilities:
            doc.add_heading("Vulnerability Details", level=1)
            doc.add_paragraph("No vulnerabilities were identified during this assessment.")
            return
        
        # Sort vulnerabilities by severity
        severity_order = {'Critical': 0, 'High': 1, 'Medium': 2, 'Low': 3}
        vulnerabilities.sort(key=lambda x: severity_order.get(x.get('severity', 'Low'), 3))
        
        doc.add_heading("Detailed Vulnerability Analysis", level=1)
        
        for i, vuln in enumerate(vulnerabilities, 1):
            self._add_vulnerability_section(doc, vuln, i)
    
    def _add_vulnerability_section(self, doc: Document, vuln: Dict[str, Any], index: int):
        """Add detailed section for a single vulnerability."""
        # Vulnerability title
        title = f"{index}. {vuln.get('type', 'Unknown Vulnerability')}"
        heading = doc.add_heading(title, level=2)
        
        # Severity badge
        severity = vuln.get('severity', 'Low')
        severity_para = doc.add_paragraph()
        severity_run = severity_para.add_run(f"Severity: {severity}")
        severity_run.font.bold = True
        
        if severity == 'Critical':
            severity_run.font.color.rgb = RGBColor(204, 0, 0)
        elif severity == 'High':
            severity_run.font.color.rgb = RGBColor(255, 102, 0)
        elif severity == 'Medium':
            severity_run.font.color.rgb = RGBColor(255, 204, 0)
        else:
            severity_run.font.color.rgb = RGBColor(0, 153, 0)
        
        # Description
        doc.add_heading("Description", level=3)
        description = vuln.get('description', 'No description available.')
        doc.add_paragraph(description)
        
        # Impact
        doc.add_heading("Impact", level=3)
        impact = self._get_impact_description(vuln)
        doc.add_paragraph(impact)
        
        # Affected Endpoints
        doc.add_heading("Affected Endpoints", level=3)
        url = vuln.get('url', 'Not specified')
        doc.add_paragraph(f"• {url}")
        
        # Reproduction Steps
        doc.add_heading("Reproduction Steps", level=3)
        steps = self._get_reproduction_steps(vuln)
        for step in steps:
            doc.add_paragraph(step, style='List Number')
        
        # Proof of Concept
        if vuln.get('payload'):
            doc.add_heading("Proof of Concept", level=3)
            poc_para = doc.add_paragraph()
            poc_run = poc_para.add_run(f"Payload: {vuln['payload']}")
            poc_run.font.name = 'Courier New'
            poc_run.font.size = Pt(10)
        
        # Remediation
        doc.add_heading("Remediation", level=3)
        remediation = self._get_remediation_advice(vuln)
        doc.add_paragraph(remediation)
        
        # References
        doc.add_heading("References", level=3)
        references = self._get_references(vuln)
        for ref in references:
            doc.add_paragraph(ref, style='List Bullet')
        
        doc.add_paragraph()  # Add spacing between vulnerabilities
    
    def _get_impact_description(self, vuln: Dict[str, Any]) -> str:
        """Generate impact description based on vulnerability type."""
        vuln_type = vuln.get('type', '').lower()
        
        impact_descriptions = {
            'sql injection': "This vulnerability allows attackers to manipulate database queries, potentially leading to data theft, data corruption, or complete database compromise. Attackers may gain unauthorized access to sensitive information or administrative privileges.",
            'cross-site scripting': "This vulnerability allows attackers to inject malicious scripts into web pages viewed by other users. This can lead to session hijacking, credential theft, defacement, or malware distribution.",
            'csrf': "This vulnerability allows attackers to perform unauthorized actions on behalf of authenticated users. Attackers could modify user data, perform financial transactions, or change account settings without the user's knowledge.",
            'directory traversal': "This vulnerability allows attackers to access files and directories outside the intended directory structure. Attackers may read sensitive files, configuration files, or source code.",
            'authentication bypass': "This vulnerability allows attackers to bypass authentication mechanisms and gain unauthorized access to protected resources or user accounts.",
            'session management': "This vulnerability in session management can lead to session hijacking, session fixation, or unauthorized access to user accounts.",
            'ssl/tls': "Weak SSL/TLS configuration can lead to man-in-the-middle attacks, data interception, or impersonation of the legitimate server.",
            'security headers': "Missing or misconfigured security headers can expose the application to various attacks including clickjacking, MIME type sniffing, and XSS.",
        }
        
        for key, description in impact_descriptions.items():
            if key in vuln_type:
                return description
        
        return "This vulnerability may allow attackers to compromise the security of the application, potentially leading to unauthorized access, data theft, or service disruption."
    
    def _get_reproduction_steps(self, vuln: Dict[str, Any]) -> List[str]:
        """Generate reproduction steps based on vulnerability type."""
        base_steps = [
            "Identify the vulnerable endpoint or parameter",
            "Craft an appropriate payload for the vulnerability type",
            "Submit the payload through the identified attack vector",
            "Observe the application's response",
            "Verify the vulnerability through additional testing"
        ]
        
        vuln_type = vuln.get('type', '').lower()
        
        if 'sql injection' in vuln_type:
            base_steps.insert(1, "Test with basic SQL injection payloads (', \", ;, --)")
            base_steps.insert(2, "Attempt to extract database information using UNION queries")
        
        elif 'xss' in vuln_type:
            base_steps.insert(1, "Test with basic XSS payloads (<script>alert(1)</script>)")
            base_steps.insert(2, "Verify payload execution in different contexts (reflected, stored, DOM)")
        
        elif 'csrf' in vuln_type:
            base_steps = [
                "Identify state-changing operations (forms, API endpoints)",
                "Create a malicious HTML page with a form targeting the vulnerable endpoint",
                "Include the victim's session cookie or authentication token",
                "Trick an authenticated user into visiting the malicious page",
                "Verify that the action is performed without the user's explicit consent"
            ]
        
        return base_steps
    
    def _get_remediation_advice(self, vuln: Dict[str, Any]) -> str:
        """Generate remediation advice based on vulnerability type."""
        vuln_type = vuln.get('type', '').lower()
        
        remediation_advice = {
            'sql injection': """
• Use parameterized queries or prepared statements for all database interactions
• Implement proper input validation and sanitization
• Use the principle of least privilege for database accounts
• Consider using an ORM that handles SQL injection prevention
• Implement web application firewall (WAF) rules to block SQL injection attempts
• Regular security testing and code reviews
""",
            'cross-site scripting': """
• Implement proper output encoding for all user-controlled data
• Use Content Security Policy (CSP) headers to prevent XSS
• Validate and sanitize all user inputs
• Use context-appropriate encoding (HTML, JavaScript, CSS, URL)
• Implement HttpOnly flags for sensitive cookies
• Regular security testing and code reviews
""",
            'csrf': """
• Implement CSRF tokens for all state-changing operations
• Use SameSite cookie attributes
• Verify the Origin and Referer headers
• Implement double-submit cookie pattern
• Use custom headers for AJAX requests
• Educate users about CSRF attacks
""",
            'directory traversal': """
• Implement proper input validation for file paths
• Use whitelist-based file access controls
• Sanitize file paths and remove directory traversal sequences
• Run the application with minimal file system permissions
• Use chroot or containerization to limit file system access
• Regular security testing and code reviews
""",
        }
        
        for key, advice in remediation_advice.items():
            if key in vuln_type:
                return advice.strip()
        
        return """
• Implement proper input validation and sanitization
• Use secure coding practices and frameworks
• Implement defense in depth security controls
• Regular security testing and penetration testing
• Keep all software components up to date
• Implement proper error handling and logging
• Use security headers and HTTPS
"""
    
    def _get_references(self, vuln: Dict[str, Any]) -> List[str]:
        """Generate relevant references for the vulnerability."""
        vuln_type = vuln.get('type', '').lower()
        
        references = [
            "OWASP Top 10 - https://owasp.org/www-project-top-ten/",
            "CWE (Common Weakness Enumeration) - https://cwe.mitre.org/",
        ]
        
        if 'sql injection' in vuln_type:
            references.extend([
                "OWASP SQL Injection Prevention Cheat Sheet - https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html",
                "CWE-89: Improper Neutralization of Special Elements used in an SQL Command - https://cwe.mitre.org/data/definitions/89.html"
            ])
        elif 'xss' in vuln_type:
            references.extend([
                "OWASP XSS Prevention Cheat Sheet - https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
                "CWE-79: Improper Neutralization of Input During Web Page Generation - https://cwe.mitre.org/data/definitions/79.html"
            ])
        elif 'csrf' in vuln_type:
            references.extend([
                "OWASP CSRF Prevention Cheat Sheet - https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html",
                "CWE-352: Cross-Site Request Forgery - https://cwe.mitre.org/data/definitions/352.html"
            ])
        
        return references
    
    def _add_recommendations(self, doc: Document):
        """Add security recommendations section."""
        doc.add_heading("Security Recommendations", level=1)
        
        recommendations_text = """
Based on the findings of this security assessment, the following recommendations are provided 
to improve the overall security posture of the application:

**Immediate Actions (Critical & High Severity)**
• Address all critical and high-severity vulnerabilities immediately
• Implement emergency patches for issues that could lead to data breach
• Review and strengthen authentication and authorization mechanisms
• Implement proper input validation and output encoding

**Short-term Improvements (Medium Severity)**
• Develop a comprehensive security testing program
• Implement automated security scanning in the CI/CD pipeline
• Establish a vulnerability management process
• Provide security awareness training for development teams

**Long-term Security Enhancements**
• Implement a security-by-design approach in development
• Establish regular penetration testing schedule
• Implement a bug bounty program for continuous security testing
• Develop incident response procedures
• Implement security monitoring and logging

**Best Practices**
• Follow OWASP Secure Coding Practices
• Implement defense in depth security controls
• Regular security assessments and updates
• Maintain an inventory of all software components
• Implement proper access controls and least privilege principle
"""
        
        doc.add_paragraph(recommendations_text)
    
    def _add_appendix(self, doc: Document, scan_results: Dict[str, Any]):
        """Add appendix with technical details."""
        doc.add_heading("Appendix A: Technical Details", level=1)
        
        # Scan information
        doc.add_heading("Scan Information", level=2)
        
        scan_info = f"""
Target: {scan_results.get('target', 'Not specified')}
Scan Date: {scan_results.get('scan_time', 'Not specified')}
Scan Duration: {scan_results.get('scan_duration', 'Not specified')}
Total Vulnerabilities: {len(scan_results.get('vulnerabilities', []))}
Scanner Version: BugHunter Professional Scanner v1.0.0
"""
        
        doc.add_paragraph(scan_info)
        
        # Network information
        if scan_results.get('reconnaissance'):
            doc.add_heading("Network Reconnaissance Results", level=2)
            recon_data = json.dumps(scan_results['reconnaissance'], indent=2)
            recon_para = doc.add_paragraph()
            recon_run = recon_para.add_run(recon_data)
            recon_run.font.name = 'Courier New'
            recon_run.font.size = Pt(9)
        
        # Raw scan data
        doc.add_heading("Raw Scan Data", level=2)
        doc.add_paragraph("Complete scan results in JSON format:")
        
        # Create a code block for the JSON data
        json_data = json.dumps(scan_results, indent=2, default=str)
        json_para = doc.add_paragraph()
        json_run = json_para.add_run(json_data)
        json_run.font.name = 'Courier New'
        json_run.font.size = Pt(8)
